sudo: false
env:  
  global:
    - CODECOV_TOKEN: 9ac43f95-d818-4e39-b43b-9f26a5d90e2f
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

install:
  - npm install

script:
  - istanbul cover node_modules/mocha/bin/_mocha
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

