language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "0.4"
  - "0.5"
  - "0.6"

install:
  - npm install

script:
  - npm run codecov

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
