sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

install:
  - npm install
  
script:
  - npm run codecov

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"